# Generated by Django 5.2.11 on 2026-03-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, choices=[('patient_change', 'Paciente modifica fecha de cita'), ('doctor_change', 'Doctor modifica fecha de cita'), ('patient_cancel', 'Paciente cancela')], max_length=30, null=True),
        ),
    ]
